# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rasterize <- function(verts, inds, texcoords, normals, nx, ny, texture_location, normal_texture_location, specular_texture_location, lookfrom, lookat, fov, light_direction, ambient_color, exponent, specular_intensity, diffuse_intensity, near_clip = 0.1, far_clip = 100) {
    .Call(`_raysterizer_rasterize`, verts, inds, texcoords, normals, nx, ny, texture_location, normal_texture_location, specular_texture_location, lookfrom, lookat, fov, light_direction, ambient_color, exponent, specular_intensity, diffuse_intensity, near_clip, far_clip)
}

wireframe <- function(verts, inds, nx, ny) {
    .Call(`_raysterizer_wireframe`, verts, inds, nx, ny)
}

