# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rasterize <- function(mesh, nx, ny, model_color, lookfrom, lookat, fov, light_direction, ambient_color, exponent, specular_intensity, diffuse_intensity, emission_intensity, typevals, has_shadow_map, calc_ambient, tbn, ambient_radius, shadow_map_bias, numbercores, max_indices, has_normals_vec, has_tex_vec, near_clip = 0.1, far_clip = 100) {
    .Call(`_raysterizer_rasterize`, mesh, nx, ny, model_color, lookfrom, lookat, fov, light_direction, ambient_color, exponent, specular_intensity, diffuse_intensity, emission_intensity, typevals, has_shadow_map, calc_ambient, tbn, ambient_radius, shadow_map_bias, numbercores, max_indices, has_normals_vec, has_tex_vec, near_clip, far_clip)
}

tonemap_image <- function(routput, goutput, boutput, toneval) {
    .Call(`_raysterizer_tonemap_image`, routput, goutput, boutput, toneval)
}

wireframe <- function(verts, inds, nx, ny) {
    .Call(`_raysterizer_wireframe`, verts, inds, nx, ny)
}

